/*
** Script de criação e população das tabelas do sistema com dados ficticios
*/

DROP DATABASE SGV_DEV

CREATE DATABASE SGV_DEV

USE SGV_DEV

CREATE TABLE TIPO_USUARIO(
    COD_TIPO_USUARIO INT PRIMARY KEY INDENTITY(1,1),
    NOME_TIPO_USUARIO VARCHAR(64) UNIQUE NOT NULL,
    STATUS CHAR NOT NULL,
    DATA_CRIACAO DATETIME NOT NULL,
    DATA_INATIVCAO DATETIME
)

INSERT INTO TIPO_USUARIO VALUES ('Administrador','A',getdate(),null)
INSERT INTO TIPO_USUARIO VALUES ('Usuario Padrão', 'A', getdate(), null)
INSERT INTO TIPO_USUARIO VALUES ('Usuario Somente Leitura', 'A', getdate(), null)

CREATE TABLE TIPO_EVENTO(
    COD_TIPO_EVENTO INT PRIMARY KEY IDENTITY(1,1),
    NOME_TIPO_EVENTO VARCHAR(64) UNIQUE NOT NULL,
    DESCRICAO VARCHAR(128) NOT NULL,
    DATA_CRIACAO DATETIME NOT NULL,
    DATA_INATIVACAO DATETIME
)

INSERT INTO TIPO_EVENTO VALUES ('EXTERNO','EVENTOS REALIZADOS FORA DA SEDE DA ONG', getdate(),null)
INSERT INTO TIPO_EVENTO VALUES ('INTERNO', 'EVENTOS REALIZADOS NA SEDE DA ONG', getdate(), null)

CREATE TABLE TIPO_VOLUNTARIO(
    COD_TIPO_VOLUNTARIO INT PRIMARY KEY IDENTITY(1,1),
    NOME_TIPO_VOLNTARIO INT PRIMARY KEY IDENTITY(1,1),
)

INSERT INTO TIPO_VOLUNTARIO VALUES ('GESTÃO')
INSERT INTO TIPO_VOLUNTARIO VALUES ('INTERNO')
INSERT INTO TIPO_VOLUNTARIO VALUES ('EXTERNO')

CREATE TABLE VOLUNTARIO(
    CPF VARCHAR(11) PRIMARY KEY,
    PRIMEIRO_NOME VARCHAR(64) NOT NULL,
    ULTIMO_NOME VARCHAR(64) NOT NULL,
    DATA_NASC DATE NOT NULL,
    DOC_IDENTIFICACAO VARCHAR(32) NOT NULL,
    TIPO_DOC_IDENTIFICACAO CHAR NOT NULL,
    DATA_EMISSAO DATE NOT NULL,
    --ORGAO_EMISSOR VARCHAR(64) NOT NULL
    NACIONALIDADE VARCHAR(64) NOT NULL,
    TELEFONE_CONTATO VARCHAR(64) NOT NULL,
    TELEFONE_CONTATO2 VARCHAR(64),
    EMAIL VARCHAR(128) NOT NULL,
    DATA_ADESAO DATE NOT NULL,
    PATH_FOTO VARCHAR(256),
    DATA_CRIACAO DATETIME NOT NULL,
    TIPO_VOLUNTARIO INT,
    FOREIGN KEY(TIPO_VOLUNTARIO) REFERENCES TIPO_VOLUNTARIO(COD_TIPO_VOLUNTARIO)
)

INSERT INTO VOLUNTARIO VALUES ('20132467801','João', 'Da Silva','1989-09-03','323459871','R','2014-02-10','Brasileira','11967564321',null,'joaosilva89@zipmail.com','2009-10-01',null,getdate(),1)
INSERT INTO VOLUNTARIO VALUES ('34567523491', 'Paula', 'Farias','1991-07-05','315674561','R','2011-06-03','Brasileira','11998564371','11987654439','paula.mfarias@ibest.com.br','2011-01-23',null,getdate(),2)
INSERT INTO VOLUNTARIO VALUES ('45678678890','Yara', 'Ribeiro', '1985-09-21', '096756768','R','2010-05-25','Brasileira','1132456544','11978654433','yara85ribeiro@bol.com.br','2011-10-23', null,getdate(),2)

CREATE TABLE TERMO_ADSAO(
    VOLUNTARIO VARCHAR(11),
    PATH_TERMO VARCHAR(256),
    STATUS CHAR NOT NULL,
    FOREIGN KEY(VOLUNTARIO) REFERENCES VOLUNTARIO(CPF)
) 


CREATE TABLE ENDERECO(
    CPF VARCHAR(11),
    COD_POSTAL VARCHAR(64),
    LOGRADOURO VARCHAR(128),
    NUMERO VARCHAR(12),
    COMPLEMENTO VARCHAR(12),
    BAIRRO VARCHAR(128),
    CIDADE VARCHAR(128),
    ESTADO_PROVINCIA VARCHAR(128),
    PAIS VARCHAR(128),
    FOREIGN KEY(CPF) REFERENCES VOLUNTARIO(CPF)
)

INSERT INTO ENDERECO VALUES ('20132467801','02434031', 'Rua dos Simões', '13', null,'Santa Monica','Aruja','São Paulo','Brasil')
INSERT INTO ENDERECO VALUES ('34567523491', '12334786', 'Avenida Agua de Haia', '13442', 'Fundos', 'Itaquera', 'São Paulo', 'São Paulo', 'Brasil')
INSERT INTO ENDERECO VALUES ('45678678890','12334566', 'Rua Cordoba', '234', 'Apto 12', 'Itaquera', 'São Paulo', 'São Paulo', 'Brasil')

CREATE TABLE EVENTO(
  COD_EVENTO INT PRIMARY KEY IDENTITY(1,1),
  NOME_EVENTO VARCHAR(64) UNIQUE NOT NULL,
  DATA_INICIO DATE NOT NULL,
  DATA_FIM DATE NOT NULL,
  ENDERECO VARCHAR(256),
  STATUS CHAR NOT NULL,
  DATA_CRIACAO DATETIME NOT NULL,
  DATA_INATIVACAO DATETIME,
  TIPO_EVENTO INT,
  FOREIGN KEY(TIPO_EVENTO) REFERENCES TIPO_EVENTO(COD_TIPO_EVENTO)
)

INSERT INTO EVENTO VALUES ('Entrega do Dia 12/05', '2017-05-12', '2017-05-12', 'Praça da Republica', 'A', getdate(),null,'1')
INSERT INTO EVENTO VALUES ('Assembleia geral - Janeiro/18','2018-01-16','2018-01-16', 'Sede da Ong','A',getdate(),2)

CREATE TABLE USUARIO(
    COD_USUARIO INT PRIMARY KEY IDENTITY(1,1),
    VOLUNTARIO VARCHAR(11),
    LOGIN_NAME VARCHAR(64) NOT NULL UNIQUE,
    PASSWD VARCHAR(255) NOT NULL,
    TIPO_USUARIO INT,
    STATUS CHAR NOT NULL,
    DATA_CRIACAO DATETIME NOT NULL,
    DATA_INATIVACAO DATETIME,
    QTD_FALHAS_LOGIN INT,
    DATA_BLOQUEIO DATETIME,
    FOREIGN KEY(VOLUNTARIO) REFERENCES VOLUNTARIO(CPF),
    FOREIGN KEY(TIPO_USUARIO) REFERENCES TIPO_USUARIO(COD_TIPO_USUARIO)
)

CREATE TABLE LOGS_APLICACAO(
    SEQUENCIAL_OCORRENCIA INT PRIMARY KEY IDENTITY(1,1),
    USUARIO INT,
    DATA_OCORENCIA DATETIME NOT NULL,
    DESCRICAO_OCORRENCIA VARCHAR(255) NOT NULL
);

GO
--CRIAÇÃO DAS FUNÇOES E PROCEDIMENTOS
--FUNCTION LOGIN
CREATE FUNCTION sf_sgv_login(@login VARCHAR(64), @passwd VARCHAR(64))
RETURNS VARCHAR(64)
AS
BEGIN
    DECLARE @varRetorno VARCHAR(64)
    IF(SELECT LOGIN_NAME FROM USUARIO WHERE LOGIN_NAME = @login) IS NOT NULL
    BEGIN
        DECLARE @varStatus CHAR
        SET @varStatus = (SELECT STATUS FROM USUARIO WHERE LOGIN_NAME = @login)
        IF @varStatus <> 'A'
        BEGIN
            IF @varStatus = 'B'
            BEGIN
                SET @varRetorno = 'BLOQUEADO'
            END
            IF @varStatus = 'I'
            BEGIN
                SET @varRetorno = 'INATIVO'
            END
        END
        ELSE
        BEGIN
            
        END
    END
END
