/*Estrutura da base de dados
DATA:08/04/2018
*/


--1
CREATE TABLE TIPO_USUARIO(
  COD_TIPO_USUARIO INT PRIMARY KEY IDENTITY(1,1),
  NOME_TIPO_USUARIO VARCHAR(64) UNIQUE NOT NULL,
  STATUS CHAR NOT NULL,
  DATA_CRIACAO DATETIME NOT NULL,
  DATA_INATIVACAO DATETIME
)


--2
CREATE TABLE TIPO_EVENTO(
  COD_TIPO_EVENTO INT PRIMARY KEY IDENTITY(1,1),
  NOME_TIPO_EVENTO VARCHAR(64) UNIQUE NOT NULL,
  DESCRICAO VARCHAR(128) NOT NULL,
  DATA_CRIACAO DATETIME NOT NULL,
  DATA_INATIVACAO DATETIME
)
--3
CREATE TABLE TIPO_ATIVIDADE(
  COD_TIPO_ATIVIDADE INT PRIMARY KEY IDENTITY(1,1),
  NOME_TIPO_ATIVIDADE VARCHAR(64) UNIQUE NOT NULL,
  DESCRICAO VARCHAR(128) UNIQUE NOT NULL,
  DATA_CRIACAO DATETIME NOT NULL,
  DATA_INATIVACAO DATETIME
)

--4
CREATE TABLE TIPO_VOLUNTARIO(
  COD_TIPO_VOLUNTARIO INT PRIMARY KEY IDENTITY(1,1),
  NOME_TIPO_VOLUNTARIO VARCHAR(64) NOT NULL UNIQUE
)

--5
CREATE TABLE VOLUNTARIO(
  CPF VARCHAR(11) PRIMARY KEY,
  PRIMEIRO_NOME VARCHAR(64) NOT NULL,
  UTIMO_NOME VARCHAR(64) NOT NULL,
  DATA_NASC DATE NOT NULL,
  DOC_IDENTIFICACAO VARCHAR(32) NOT NULL,
  TIPO_DOC_IDENTFICACAO CHAR NOT NULL,
  DATA_EMISSAO DATE NOT NULL,
  NACIONALIDADE VARCHAR(64),
  TELEFONE_CONTATO VARCHAR(64) NOT NULL,
  TELEFONE_CONTATO2 VARCHAR(64),
  EMAIL VARCHAR(64),
  DATA_ADESAO DATE NOT NULL,
  PATH_FOTO VARCHAR(128),
  DATA_CRIACAO DATETIME NOT NULL,
  STATUS CHAR NOT NULL,
  DATA_INATIVACAO DATETIME,
  TIPO_VOLUNTARIO INT,
  FOREIGN KEY(TIPO_VOLUNTARIO) REFERENCES TIPO_VOLUNTARIO(COD_TIPO_VOLUNTARIO)
)

--6
CREATE TABLE TERMO_ADESAO(
  CPF VARCHAR(11),
  PATH_TERMO VARCHAR(128),
  STATUS CHAR NOT NULL,
  FOREIGN KEY(CPF) REFERENCES VOLUNTARIO(CPF)
)

--7
CREATE TABLE ENDERECO(
  CPF VARCHAR(11),
  COD_POSTAL  VARCHAR(64),
  LOGRADOURO VARCHAR(128),
  NUMERO VARCHAR(12),
  COMPLEMENTO VARCHAR(12),
  CIDADE VARCHAR(128),
  ESTADO_PROVINCIA VARCHAR(128),
  PAIS VARCHAR(128),
  FOREIGN KEY(CPF) REFERENCES VOLUNTARIO(CPF)
)

--8
CREATE TABLE EVENTO(
  COD_EVENTO INT PRIMARY KEY IDENTITY(1,1),
  NOME_EVENTO VARCHAR(64) UNIQUE NOT NULL,
  DATA_INICIO DATE NOT NULL,
  DATA_FIM DATE NOT NULL,
  STATUS CHAR NOT NULL,
  DATA_CRIACAO DATETIME NOT NULL,
  DATA_INATIVACAO DATETIME,
  TIPO_EVENTO INT,
  FOREIGN KEY(TIPO_EVENTO) REFERENCES TIPO_EVENTO(COD_TIPO_EVENTO)
)

--9
CREATE TABLE ATIVIDADE(
  COD_ATIVIDADE INT PRIMARY KEY IDENTITY(1,1),
  NOME_ATIVIDADE VARCHAR(64) NOT  NULL,
  QTD_VOLUNTARIOS INT NOT NULL,
  DURACAO_MEDIA_MINUTOS INT NOT NULL,
  STATUS CHAR NOT NULL,
  DATA_CRIACAO DATETIME NOT NULL,
  DATA_INATIVACAO DATETIME,
  TIPO_ATIVIDADE INT,
  FOREIGN KEY(TIPO_ATIVIDADE) REFERENCES TIPO_ATIVIDADE(COD_TIPO_ATIVIDADE)
)

--10
CREATE TABLE ATRIBUICAO_VOLUNTARIO_ATIVIDADE(
  COD_ATRIBUICAO INT PRIMARY KEY IDENTITY(1,1),
  VOLUNTARIO VARCHAR(11),
  ATIVIDADE INT,
  STATUS CHAR NOT NULL,
  DATA_RESPOSTA DATETIME,
  FOREIGN KEY(VOLUNTARIO) REFERENCES VOLUNTARIO(CPF),
  FOREIGN KEY(ATIVIDADE) REFERENCES ATIVIDADE(COD_ATIVIDADE)
)

--11
CREATE TABLE HORAS_DECLARADAS(
  COD_DECLARACAO_HORAS INT PRIMARY KEY IDENTITY(1,1),
  ATIVIDADE_VOLUNTARIO INT,
  DATA_dDECLARACAO DATETIME NOT NULL,
  QTD_HORAS_DECLARADAS REAL,
  FOREIGN KEY(ATIVIDADE_VOLUNTARIO) REFERENCES ATRIBUICAO_VOLUNTARIO_ATIVIDADE(COD_ATRIBUICAO)
  
)


--12
CREATE TABLE ATRIBUICAO_ATIVIDADE_PARA_EVENTO(
  COD_EVENTO INT,
  COD_ATIVIDADE INT,
  DATA_ATRIBUICAO DATETIME NOT NULL
  FOREIGN KEY(COD_EVENTO) REFERENCES EVENTO(COD_EVENTO),
  FOREIGN KEY(COD_ATIVIDADE) REFERENCES ATIVIDADE(COD_ATIVIDADE)

)



--13
CREATE TABLE USUARIO(
  COD_USUARIO INT PRIMARY KEY IDENTITY(1,1),
  VOLUNTARIO VARCHAR(11),
  LOGIN_NAME VARCHAR(64) UNIQUE NOT NULL,
  PASSWD VARCHAR(64) NOT NULL,
  TIPO_USUARIO INT,
  STATUS CHAR NOT NULL,
  DATA_CRIACAO DATETIME NOT NULL,
  QTD_FALHAS_LOGIN INT,
  DATA_BLOQUEIO DATETIME,
  FOREIGN KEY(VOLUNTARIO) REFERENCES VOLUNTARIO(CPF),
  FOREIGN KEY(TIPO_USUARIO) REFERENCES TIPO_USUARIO(COD_TIPO_USUARIO)
 )

--14
 CREATE TABLE LOGS_APP(
    COD_OCORRENCIA INT PRIMARY KEY IDENTITY(1,1),
    USUARIO INT,
    DATA_OCORRENCIA DATETIME NOT NULL,
    DESCRICAO_OCORRENCIA VARCHAR NOT NULL,
    FOREIGN KEY(USUARIO) REFERENCES USUARIO(COD_USUARIO)
 )
