-- CRIACAO DAS TABELAS USUARIO E TIPO USUARIO
--DATA 02/04/2018
--POR MARCELO RIBEIRO
--VERSAO 0.1

CREATE TABLE TIPO_USUARIO(
  COD_TIPO_USUARIO INT PRIMARY KEY IDENTITY(1,1),
  NOME_TIPO_USUARIO  VARCHAR(64) NOT NULL UNIQUE,
  STATUS CHAR NOT NULL,
  DATA_CRIACAO DATETIME NOT NULL,
  DATA_INATIVACAO DATETIME
)

CREATE TABLE USUARIO(
  COD_USUARIO INT PRIMARY KEY IDENTITY(1,1),
  LOGIN_NAME VARCHAR(64) NOT NULL UNIQUE,
  PASSWD VARCHAR(64) NOT NULL
  STATUS CHAR NOT NULL,
  DATA_CRIACAO DATETIME NOT NULL,
  DATA_INATIVACAO DATETIME
  QTD_TENTATIVAS_ERRADAS INT,
  DATA_BLOQUEIO DATETIME
  TIPO_USUARIO INT,
  FOREGIN KEY(TIPO_USUARIO) REFERENCES TIPO_USUARIO(COD_TIPO_USUARIO)
);
